services:
  frontend:
    image: gonzalog97/frontend:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 30s

  cypress:
    build:
      context: ./  # Directorio raíz del proyecto Cypress
      dockerfile: dockerfile  # Ruta relativa al Dockerfile
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - ./cypress:/e2e  # Monta el directorio cypress en /e2e
    working_dir: /e2e  # El directorio de trabajo dentro del contenedor
    entrypoint: ["npx", "cypress", "run"]
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
