version: '3.8'

services:
  frontend:
    build:
      context: https://github.com/gonzabgarcia/frontend-qa-automation  # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 30s

  cypress:
    image: cypress/included:13.13.1
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - ./e2e:/e2e
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run"]
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
