services:
  frontend:
    image: gonzalog97/frontend:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 30s

  cypress:
    build:
      context: .  # Usa el contexto de construcción correcto
      dockerfile: dockerfile
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - .:/e2e  # Monta el directorio de Cypress
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run"]
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
