version: '2.29.1'  # Asegúrate de usar una versión compatible

services:
  frontend:
    build:
      context: ../frontend-qa-automation  # Ruta al directorio del frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 30s

  cypress:
    image: cypress/included:14.0.0
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - .:/e2e
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run"]
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
