services:
  cypress:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - .:/e2e
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run"]
    environment:
      - CYPRESS_baseUrl=http://frontend:3000

  frontend:
    image: gonzalob97/frontend:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 30s
