name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.0
        options: --privileged
        ports:
          - 3000:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose v2
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/2.20.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Install Cypress dependencies
        run: docker-compose run cypress npm ci

      - name: Run Cypress tests
        run: docker-compose run cypress npx cypress run

      - name: Stop Docker containers
        run: docker-compose down
