name: Run Cypress Tests

on:
  workflow_run:
    workflows: ["Build and Push Frontend Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 3000:3000

    steps:
      # Step to checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up Docker Buildx, a Docker CLI plugin for extended build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step to install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step to log in to DockerHub using secrets for username and password
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step to check if the frontend container is already running
      - name: Check if Frontend is Running
        id: check_frontend
        run: |
          if docker ps -q -f name=frontend | grep -q .; then
            echo "Frontend is already running"
            echo "FRONTEND_RUNNING=true" >> $GITHUB_ENV
          else

            echo "Frontend is not running"
            echo "FRONTEND_RUNNING=false" >> $GITHUB_ENV
          fi

      # Step to build and run Docker containers if the frontend is not running
      - name: Build and run Docker containers if Frontend is not running
        if: ${{ env.FRONTEND_RUNNING == 'false' }}
        run: |
          docker-compose -f docker-compose.yml up -d

      # Step to install Cypress dependencies inside the Cypress container
      - name: Install Cypress dependencies
        run: docker-compose exec cypress npm ci

      # Step to run Cypress tests inside the Cypress container
      - name: Run Cypress tests
        run: docker-compose exec cypress npx cypress run

      # Step to stop Docker containers if the frontend was not running initially
      - name: Stop Docker containers
        if: ${{ env.FRONTEND_RUNNING == 'false' }}
        run: docker-compose down